################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
hal_stm_lvgl \
hal_stm_lvgl/tft \
hal_stm_lvgl/touchpad \
lvgl/examples/anim \
lvgl/examples/assets \
lvgl/examples/assets/emoji \
lvgl/examples/event \
lvgl/examples/get_started \
lvgl/examples/layouts/flex \
lvgl/examples/layouts/grid \
lvgl/examples/libs/bmp \
lvgl/examples/libs/ffmpeg \
lvgl/examples/libs/freetype \
lvgl/examples/libs/gif \
lvgl/examples/libs/png \
lvgl/examples/libs/qrcode \
lvgl/examples/libs/rlottie \
lvgl/examples/libs/sjpg \
lvgl/examples/others/fragment \
lvgl/examples/others/gridnav \
lvgl/examples/others/imgfont \
lvgl/examples/others/monkey \
lvgl/examples/others/msg \
lvgl/examples/others/snapshot \
lvgl/examples/porting \
lvgl/examples/scroll \
lvgl/examples/styles \
lvgl/examples/widgets/animimg \
lvgl/examples/widgets/arc \
lvgl/examples/widgets/bar \
lvgl/examples/widgets/btn \
lvgl/examples/widgets/btnmatrix \
lvgl/examples/widgets/calendar \
lvgl/examples/widgets/canvas \
lvgl/examples/widgets/chart \
lvgl/examples/widgets/checkbox \
lvgl/examples/widgets/colorwheel \
lvgl/examples/widgets/dropdown \
lvgl/examples/widgets/img \
lvgl/examples/widgets/imgbtn \
lvgl/examples/widgets/keyboard \
lvgl/examples/widgets/label \
lvgl/examples/widgets/led \
lvgl/examples/widgets/line \
lvgl/examples/widgets/list \
lvgl/examples/widgets/menu \
lvgl/examples/widgets/meter \
lvgl/examples/widgets/msgbox \
lvgl/examples/widgets/obj \
lvgl/examples/widgets/roller \
lvgl/examples/widgets/slider \
lvgl/examples/widgets/span \
lvgl/examples/widgets/spinbox \
lvgl/examples/widgets/spinner \
lvgl/examples/widgets/switch \
lvgl/examples/widgets/table \
lvgl/examples/widgets/tabview \
lvgl/examples/widgets/textarea \
lvgl/examples/widgets/tileview \
lvgl/examples/widgets/win \
lvgl/src/core \
lvgl/src/draw/arm2d \
lvgl/src/draw \
lvgl/src/draw/nxp \
lvgl/src/draw/nxp/pxp \
lvgl/src/draw/nxp/vglite \
lvgl/src/draw/sdl \
lvgl/src/draw/stm32_dma2d \
lvgl/src/draw/sw \
lvgl/src/draw/swm341_dma2d \
lvgl/src/extra/layouts/flex \
lvgl/src/extra/layouts/grid \
lvgl/src/extra/libs/bmp \
lvgl/src/extra/libs/ffmpeg \
lvgl/src/extra/libs/freetype \
lvgl/src/extra/libs/fsdrv \
lvgl/src/extra/libs/gif \
lvgl/src/extra/libs/png \
lvgl/src/extra/libs/qrcode \
lvgl/src/extra/libs/rlottie \
lvgl/src/extra/libs/sjpg \
lvgl/src/extra \
lvgl/src/extra/others/fragment \
lvgl/src/extra/others/gridnav \
lvgl/src/extra/others/imgfont \
lvgl/src/extra/others/monkey \
lvgl/src/extra/others/msg \
lvgl/src/extra/others/snapshot \
lvgl/src/extra/themes/basic \
lvgl/src/extra/themes/default \
lvgl/src/extra/themes/mono \
lvgl/src/extra/widgets/animimg \
lvgl/src/extra/widgets/calendar \
lvgl/src/extra/widgets/chart \
lvgl/src/extra/widgets/colorwheel \
lvgl/src/extra/widgets/imgbtn \
lvgl/src/extra/widgets/keyboard \
lvgl/src/extra/widgets/led \
lvgl/src/extra/widgets/list \
lvgl/src/extra/widgets/menu \
lvgl/src/extra/widgets/meter \
lvgl/src/extra/widgets/msgbox \
lvgl/src/extra/widgets/span \
lvgl/src/extra/widgets/spinbox \
lvgl/src/extra/widgets/spinner \
lvgl/src/extra/widgets/tabview \
lvgl/src/extra/widgets/tileview \
lvgl/src/extra/widgets/win \
lvgl/src/font \
lvgl/src/hal \
lvgl/src/misc \
lvgl/src/widgets \

