################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
hal_stm_lvgl \
hal_stm_lvgl/tft \
hal_stm_lvgl/touchpad \
lvgl/src/core \
lvgl/src/draw/arm2d \
lvgl/src/draw/gd32_ipa \
lvgl/src/draw \
lvgl/src/draw/nxp \
lvgl/src/draw/nxp/pxp \
lvgl/src/draw/nxp/vglite \
lvgl/src/draw/sdl \
lvgl/src/draw/stm32_dma2d \
lvgl/src/draw/sw \
lvgl/src/draw/swm341_dma2d \
lvgl/src/font \
lvgl/src/hal \
lvgl/src/layouts/flex \
lvgl/src/layouts/grid \
lvgl/src/libs/bmp \
lvgl/src/libs/ffmpeg \
lvgl/src/libs/freetype \
lvgl/src/libs/fsdrv \
lvgl/src/libs/gif \
lvgl/src/libs/png \
lvgl/src/libs/qrcode \
lvgl/src/libs/rlottie \
lvgl/src/libs/sjpg \
lvgl/src/libs/tiny_ttf \
lvgl/src/misc \
lvgl/src/others/file_explorer \
lvgl/src/others/fragment \
lvgl/src/others/gridnav \
lvgl/src/others/ime \
lvgl/src/others/imgfont \
lvgl/src/others/monkey \
lvgl/src/others/msg \
lvgl/src/others/snapshot \
lvgl/src/themes/basic \
lvgl/src/themes/default \
lvgl/src/themes/mono \
lvgl/src/widgets/animimg \
lvgl/src/widgets/arc \
lvgl/src/widgets/bar \
lvgl/src/widgets/btn \
lvgl/src/widgets/btnmatrix \
lvgl/src/widgets/calendar \
lvgl/src/widgets/canvas \
lvgl/src/widgets/chart \
lvgl/src/widgets/checkbox \
lvgl/src/widgets/colorwheel \
lvgl/src/widgets/dropdown \
lvgl/src/widgets/img \
lvgl/src/widgets/imgbtn \
lvgl/src/widgets/keyboard \
lvgl/src/widgets/label \
lvgl/src/widgets/led \
lvgl/src/widgets/line \
lvgl/src/widgets/list \
lvgl/src/widgets/menu \
lvgl/src/widgets/meter \
lvgl/src/widgets/msgbox \
lvgl/src/widgets/objx_templ \
lvgl/src/widgets/roller \
lvgl/src/widgets/slider \
lvgl/src/widgets/span \
lvgl/src/widgets/spinbox \
lvgl/src/widgets/spinner \
lvgl/src/widgets/switch \
lvgl/src/widgets/table \
lvgl/src/widgets/tabview \
lvgl/src/widgets/textarea \
lvgl/src/widgets/tileview \
lvgl/src/widgets/win \

